### ISSUE TITLE
publicsuffix is outdated and should not be used

### ISSUE THREAD

**Issue by dvzrv** [ValiMail/authentication-headers#2]
During packaging I realized, that [publicsuffix](https://pypi.org/project/publicsuffix/) is not supposed to be in use anymore.

I guess a more up-to-date and still maintained solution would be to switch to [publicsuffix2](https://pypi.org/project/publicsuffix2/) or [publicsuffixlist](https://pypi.org/project/publicsuffixlist/).

What do you think?

**Comment by kitterma** [comment]
I agree with switching, but I don't think it's urgent.  Since authentication-headers provides both a means to use a system publicsuffixlist or to update the authentication-headers copy of the data, there's no risk of being stuck with outdated data, which is the major potential problem.  For our use, publicsuffic seems to work fine.

I'd planned on updating to publicsuffix2 at some point, but haven't gotten around to it.  I'd welcome a PR to update it.  If not, I'll probably get to it eventually.

**Comment by kitterma** [comment]
I'm about to do a new release and I'll be sure to sign it to resolve this issue.

**Comment by kitterma** [comment]
I've looked into this and switching to publicsuffix2 is trivial.  I've packaged publicsuffix2 for Debian.  Once that's accepted, I'll do a new release to switch to it.

**Comment by kitterma** [comment]
If you want to do a distro patch to switch in the meantime, all you need to do is change the import in dmarc_lookup.py from publicsuffix to publicsuffix2 and change the install_requires similarly in setup.py.

**Comment by kitterma** [comment]
Switched in 0.13.0 to publicsuffix2.  Closing.
